# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "an_axe"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Peter Boling", "William B Harding"]
  s.date = "2011-11-02"
  s.description = "An Axe is a Rails3 update and Enginification of Modern Savage Beast, which is a revision\nof the old Savage Beast Plugin.\n\nSavage Beast is a Rails forum plugin based on the popular Beast plugin.\nThe Savage Beast plugin has been installed in hundreds of Rails sites, partially\nbecause it's the only viable choice for a message forum plugin, but also because\nit incorporates a lot of features that would be a time-consuming headache for you\nto implement yourself.\n\nDifferences from what may or may not be in any of the ancestors of An Axe:\n  Views are now HAML\n  I18n api for static text (no more gettext/gibberish)\n  Works with Rails 3.X and Ruby 1.9.2\n\nGoals:\n  Seamless Upgrade from some flavors of (Modern) Savage Beast"
  s.email = "peter.boling@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = `git ls-files`.split("\n")
  s.homepage = "http://github.com/pboling/an_axe"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Rails 3 Engine implementation of Modern Savage Beast"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.0.0"])
      s.add_runtime_dependency(%q<will_paginate>, ["~> 3.0.0"])
      s.add_runtime_dependency(%q<acts_as_list>, [">= 0"])
      s.add_runtime_dependency(%q<acts-as-taggable-on>, [">= 2.0"])
      s.add_runtime_dependency(%q<loofah>, [">= 1.0"])
      s.add_runtime_dependency(%q<loofah-activerecord>, [">= 1.0"])
      s.add_development_dependency(%q<rspec>, [">= 2.6.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
    else
      s.add_dependency(%q<rails>, [">= 3.0.0"])
      s.add_dependency(%q<will_paginate>, ["~> 3.0.0"])
      s.add_dependency(%q<acts_as_list>, [">= 0"])
      s.add_dependency(%q<acts-as-taggable-on>, [">= 2.0"])
      s.add_dependency(%q<loofah>, [">= 1.0"])
      s.add_dependency(%q<loofah-activerecord>, [">= 1.0"])
      s.add_dependency(%q<rspec>, [">= 2.6.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.0.0"])
    s.add_dependency(%q<will_paginate>, ["~> 3.0.0"])
    s.add_dependency(%q<acts_as_list>, [">= 0"])
    s.add_dependency(%q<acts-as-taggable-on>, [">= 2.0"])
    s.add_dependency(%q<loofah>, [">= 1.0"])
    s.add_dependency(%q<loofah-activerecord>, [">= 1.0"])
    s.add_dependency(%q<rspec>, [">= 2.6.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
  end
end

